theme: jekyll-remote-theme
title: Cisse Stanislas hippolythe
logo : Snapchat-587822044.jpg
description :  Curriculum vitae and Portfolio
description : E-mail tcharnoncisse@gmail.com
remote_theme: pages-themes/minimal@v0.2.0
