# Configuration de votre site Jekyll

title: Cisse Stanislas Hippolythe   
#logo: /Snapchat-587822044.jpg       
description: Curriculum vitae and Portfolio
email: tcharnoncisse@gmail.com       
remote_theme: jekill-theme-minimal
show_downloads: true                 
