theme: jekyll-remote-theme
title: Cisse Stanislas hippolythe
logo : /assets/Profil_photo_4.jpg
description :  Curriculum vitae and Portfolio
description : E-mail tcharnoncisse@gmail.com
remote_theme: pages-themes/minimal@v0.2.0
