# Configuration de votre site Jekyll

title: CISSE Tcharnon Stanislas Hippolythe
description: Curriculum vitae and Portfolio
email: tcharnoncisse@gmail.com
logo: /assets/photo_de_profil_cisse.jpg  
remote_theme: pages-themes/minimal@v0.2.0

